# Customer shopping behaviour analysis:

select * from cust_shop_behaviour;
describe cust_shop_behaviour;
# change column name:
alter table cust_shop_behaviour change `ï»¿Customer ID` Customer_id int;
alter table cust_shop_behaviour change `Item Purchased` item_purchased varchar(255);
alter table cust_shop_behaviour change `Subscription Status` subscription_status varchar(255);
alter table cust_shop_behaviour change `Shipping Type` shipping_type varchar(255);
alter table cust_shop_behaviour change `Discount Applied` discount_applied varchar(255);
alter table cust_shop_behaviour change `Promo Code Used` promo_code_used varchar(255);
alter table cust_shop_behaviour change `Payment Method` payment_method varchar(255);
alter table cust_shop_behaviour change `Frequency of Purchases` purchase_frequency varchar(255);
alter table cust_shop_behaviour change `Review Rating` review_rating double;
alter table cust_shop_behaviour change `Previous Purchases` previous_purchases int;
alter table cust_shop_behaviour change `Purchase Amount (USD)` purchase_amount int;

# D1 : Executive Revenue Focused:
# Objective: Check overall business performance:

# Total Revenue generated by company:
select sum(purchase_amount) as Total_revenue from cust_shop_behaviour;

# Average Order Value:
select round(avg(purchase_amount),2) as avg_order_value from cust_shop_behaviour;

# Number of new Customers:
select count(customer_id) as new_customers from (
select customer_id, previous_purchases
from cust_shop_behaviour where previous_purchases <=1)dt;

# Top revenue generating categories:
select Category, sum(purchase_amount) as revenue from cust_shop_behaviour
group by category order by revenue desc;

# top Revenue generating items and their contribution:
select item_purchased,sum(purchase_amount) as revenue,concat(format((sum(purchase_amount) 
/ sum(sum(purchase_amount)) over())*100,2),'%') as revenue_percentage
from cust_shop_behaviour
group by item_purchased 
order by revenue desc;

# revenue by location:
select Location, sum(purchase_amount) as revenue from cust_shop_behaviour
group by location order by revenue desc;

#  no. of customers with previous purchases:
select count(customer_id), previous_purchases from cust_shop_behaviour 
group by previous_purchases order by previous_purchases desc;

# subscribers vs non-subscriber revenue:
select subscription_status, sum(purchase_amount) as revenue,
count(customer_id) as Number_of_cust from cust_shop_behaviour
group by subscription_status;

# do discounted purchases generate higher revenue?:
select concat(format((sum(case when discount_applied="yes" then purchase_amount else 0 end)
/sum(purchase_amount))*100,2),'%')as Discounted_rev_perc,
concat(format((sum(case when discount_applied="no" then purchase_amount else 0 end)
/sum(purchase_amount))*100,2),'%') as no_Discounted_rev_perc
from cust_shop_behaviour;

# seasonal sales trend:
select season, sum(purchase_amount) as revenue from cust_shop_behaviour
group by season order by revenue desc;

#D2: Marketing Focused:
# Objective: Which customers should we target, what campaigns are working,
#            and how can we improve ROI while reducing discount dependency?

# which gender contributes most to revenue?:
select gender, sum(purchase_amount) as revenue from cust_shop_behaviour
group by gender order by revenue desc;

# which age group contributes most to revenue?:
select case 
when age between 18 and 25 then '18-25'
when age between 26 and 35 then '26-35'
when age between 36 and 45 then '36-45'
when age between 46 and 55 then '46-55'
when age between 56 and 70 then '56-70'
end as age_group, sum(purchase_amount) as total_revenue
from cust_shop_behaviour
group by age_group
order by total_revenue desc;

# relationship between customer purchase frequency and spending behaviour:
with customer_fmv as 
(select customer_id,
previous_purchases as frequency,
purchase_amount as monetary_value,
previous_purchases AS value_intensity
from cust_shop_behaviour)
select *,case when value_intensity > 
(select avg(value_intensity) from customer_fmv) then 'Premium Buyer'
else 'Regular Buyer'
end as spending_type
from customer_fmv;

# classifying customers into loyalty and value-tiers for targeted marketing:
with avg_values as (select avg(previous_purchases) as avg_freq,
avg(purchase_amount) as avg_amt
from cust_shop_behaviour)
select c.customer_id,c.previous_purchases,c.purchase_amount,
case when c.previous_purchases >= a.avg_freq then 'high loyalty'
else 'low loyalty' end as loyalty_segment,
case when c.purchase_amount >= a.avg_amt then 'high value'
else 'low value' end as value_segment
from cust_shop_behaviour c
cross join avg_values a;

# which payment method convert into high order values?:
select payment_method,avg(purchase_amount) as avg_spend 
from cust_shop_behaviour
group by payment_method order by avg_spend desc;

# does promo code affect revenue?:
select concat(format((sum(case when promo_code_used="yes" then purchase_amount else 0 end)
/sum(purchase_amount))*100,2),'%')as promo_code_perc
from cust_shop_behaviour;

# which purchase frequency segment drives the most revenue?
select purchase_frequency,sum(purchase_amount) as total_revenue,
concat(format((sum(purchase_amount) / sum(sum(purchase_amount)) over ()) * 100, 2),'%')
as revenue_percentage,count(distinct customer_id) as customer_count
from cust_shop_behaviour
group by purchase_frequency
order by total_revenue desc;

# creating view for age group analysis: 
create view vw_customer_age_groups as
select *,case 
when age between 18 and 25 then '18-25'
when age between 26 and 35 then '26-35'
when age between 36 and 45 then '36-45'
when age between 46 and 55 then '46-55'
when age between 56 and 70 then '56-70'
else 'unknown'end as age_group
from cust_shop_behaviour;

select * from vw_customer_age_groups;

# avg purchases by age_groups:
select age_group,avg(purchase_amount) as avg_purchase
from vw_customer_age_groups
group by age_group
order by avg_purchase desc;

# do customers who use discounts have high purchase rate?:
select discount_applied,
case 
when previous_purchases = 1 then 'new'
when previous_purchases between 2 and 5 then 'low_repeat'
when previous_purchases between 6 and 15 then 'medium_repeat'
when previous_purchases between 16 and 30 then 'high_repeat'
else 'loyal'end as purchase_segment,
count(*) as customer_count,concat(format(count(*) *100.0/
sum(count(*)) over (partition by discount_applied),2),'%') as segment_percentage
from cust_shop_behaviour
group by discount_applied, purchase_segment
order by discount_applied, purchase_segment;

# how customer purchase behaviour vary across locations:
select location, purchase_frequency, count(*) as total_customers
from cust_shop_behaviour
group by location,purchase_frequency
order by location,total_customers desc;


# D3: Product Focused:
# objective: which products and categories drive value,
#            discount dependency, customer demand analysis? 

# best selling category by age group demographic:
select age_group,category ,count(*) as customer_count
from vw_customer_age_groups
group by age_group,category
order by age_group,customer_count desc;

# seasonal product performance:
select season,category, revenue 
from (select season,category,sum(purchase_amount) as revenue,
rank() over (partition by season order by sum(purchase_amount)desc) as rnk
from cust_shop_behaviour
group by season,category)t
where t.rnk <= 2;

# do highly rated products generate more revenue:
select review_rating, round(avg(purchase_amount),2) as avg_revenue
from cust_shop_behaviour
group by review_rating
order by review_rating desc;

# are certain categories more dependent on discounts?:
select category,COUNT(*) as discounted_orders
from cust_shop_behaviour
where discount_applied = 'Yes'
group by category
order by discounted_orders desc;

# color and size demand analysis:
select color,size,count(*) as purchase_count
from cust_shop_behaviour
group by color, size
order by purchase_count desc;

# item-color-size combination most popular among cutomers:
select item_purchased,color,size,count(*) as purchase_count
from cust_shop_behaviour
group by item_purchased,color,size
order by purchase_count desc;

# top 5 items in each season:
select season, item_purchased, revenue from
(select season, item_purchased, sum(purchase_amount) as revenue,
dense_rank() over (partition by season order by sum(purchase_amount) desc) as rnk
from cust_shop_behaviour
group by season, item_purchased)t
where rnk <= 5
order by season, rnk;

# products bought be customers with high previous purchases:
select item_purchased, avg(previous_purchases) as avg_repeat_depth
from cust_shop_behaviour
group by item_purchased
having avg(previous_purchases) > (select avg(previous_purchases)
from cust_shop_behaviour)
order by avg_repeat_depth desc;

# What proportion of each product’s revenue and customers comes
# from discounted purchases:
select item_purchased,count(customer_id) as total_customers,
sum(purchase_amount) as total_revenue,
count(case when discount_applied='yes' then customer_id end) as discount_customers,
sum(case when discount_applied='yes' then purchase_amount else 0 end) as discount_revenue,
concat(round(sum(case when discount_applied='yes' then purchase_amount else 0 end)*100.0 /
sum(purchase_amount),2),'%') as discount_revenue_percent
from cust_shop_behaviour
group by item_purchased
order by discount_revenue_percent desc;


# D4: operations focused:
# objective: How efficiently is the business running,where are operational risks
#             and what process improvements are needed?

# revenue contribution by location:
select location,sum(purchase_amount) as total_revenue
from cust_shop_behaviour
group by location
order by total_revenue desc;

# shipping methods used most frequently by customers:
select shipping_type, count(*) as customers_count
from cust_shop_behaviour
group by shipping_type
order by customers_count desc;

# shipping preferences by location:
select location, shipping_type,total from
(select location,shipping_type,count(*) as total,
dense_rank() over (partition by location order by count(*) desc) as rnk
from cust_shop_behaviour
group by location, shipping_type)t
where rnk=1
order by location,total desc;

# which shipping types generates highest revenue contribution:
select shipping_type,sum(purchase_amount) as revenue,
dense_rank() over(order by sum(purchase_amount) desc) as shipping_rank
from cust_shop_behaviour
group by shipping_type;

# location with highest number of customer purchases:(demand analysis)
select location,count(*) as total_orders
from cust_shop_behaviour
group by location
order by total_orders desc;

# season with high order volume:
select season,count(*) as total_orders
from cust_shop_behaviour
group by season
order by total_orders desc;

# payment_methods most commonly used by customers:
select payment_method,count(*) as customers
from cust_shop_behaviour
group by payment_method
order by customers desc;

# which payment method contributes most to revenue:
select payment_method,sum(purchase_amount) as revenue,
dense_rank() over(order by sum(purchase_amount) desc) as shipping_rank
from cust_shop_behaviour
group by payment_method;

# locations having high concentration of high value customers:
select location, high_value_customers
from(select location,count(*) as high_value_customers,
dense_rank() over(order by count(*) desc) as rnk
from cust_shop_behaviour
where purchase_amount >(select avg(purchase_amount)
from cust_shop_behaviour)
group by location)t;

# location having high concentration of frequent buyers:
select location,count(case when purchase_frequency='weekly' then 1 end) as weekly_customers
from cust_shop_behaviour
group by location
order by weekly_customers desc;




